name: CI/CD Pipeline for Main Branch

on:
  push:
    branches:
      - main

jobs:
  update-repo:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set correct permissions for the repository on the server
      - name: Set correct permissions for the repository
        run: |
          sudo chown -R $(whoami):$(whoami) /var/www/html/raidcloudproject/web/
          sudo chmod -R u+rw /var/www/html/raidcloudproject/web/

      # Step 3: Push updates to the RHEL server repository
      - name: Push updates to the RHEL server
        run: |
          cd /var/www/html/raidcloudproject/web/
          git fetch origin main
          git reset --hard origin/main
          echo "Repository updated on the server."

  ci-pipeline:
    needs: update-repo  # This ensures ci-pipeline runs after update-repo
    runs-on: ubuntu-latest

    steps:
      # Step 4: Check out the code
      - name: Check out the repository
        uses: actions/checkout@v3
      
      # Step 5: Run Super Linter
      - name: Run Super Linter
        uses: github/super-linter@v5
        continue-on-error: true
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Run Basic Tests
      - name: Verify External URL
        run: |
          curl -I http://18.142.225.98/raidcloudproject/web/ || exit 1

      # Step 7: Perform Security Scan
      - name: Run Security Scan
        run: |
          npm install -g retire
          retire --path . --outputformat text || true

      # Step 8: Performance Benchmarking with Lighthouse
      - name: Run Lighthouse Performance Benchmark
        run: |
          # Install necessary Chrome dependencies
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          sudo apt-get install -y libnss3 libgconf-2-4 libgdk-pixbuf2.0-0 libatk1.0-0 \
            libatk-bridge2.0-0 libx11-xcb1 libxcomposite1 libxrandr2 libgbm1 libasound2 \
            libappindicator3-1 libxtst6 libxss1 libnss3-dev libnspr4-dev
          # Install Node.js and Lighthouse
          sudo apt-get install -y nodejs npm
          npm install -g lighthouse
          # Run Lighthouse on the external URL
          lighthouse http://18.142.225.98/raidcloudproject/web/ \
            --output html \
            --output-path ./lighthouse-report.html \
            --only-categories=performance \
            --chrome-flags="--headless --no-sandbox --disable-gpu --disable-software-rasterizer"
      # Step 9: Upload Lighthouse Report as Artifact
      - name: Upload Lighthouse Performance Report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: ./lighthouse-report.html
